table Base
	lineageTag: 9af3df69-6f04-469d-ab3c-e921892e482a

	column id
		dataType: string
		lineageTag: ab244d16-218a-4ce2-8564-567b5b6d2db3
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column title
		dataType: string
		lineageTag: 84f2391f-e27e-4531-ad34-cf46360d383b
		summarizeBy: none
		sourceColumn: title

		annotation SummarizationSetBy = Automatic

	column subtitle
		dataType: string
		lineageTag: 1791b466-1fc6-49b0-bff2-317fc8761161
		summarizeBy: none
		sourceColumn: subtitle

		annotation SummarizationSetBy = Automatic

	column cardNumber
		dataType: string
		lineageTag: 4dd82063-7188-40ec-9aba-3d74c2dcbe5b
		summarizeBy: none
		sourceColumn: cardNumber

		annotation SummarizationSetBy = Automatic

	column cardCount
		dataType: string
		lineageTag: 5dad85ee-75a4-405b-ab7a-c7219130b83f
		summarizeBy: none
		sourceColumn: cardCount

		annotation SummarizationSetBy = Automatic

	column artist
		dataType: string
		lineageTag: 35cea52e-7e1c-4a23-bf05-187bfbbceead
		summarizeBy: none
		sourceColumn: artist

		annotation SummarizationSetBy = Automatic

	column artFrontHorizontal
		dataType: string
		lineageTag: b14cc233-79b5-4760-82a2-a4f0e287357f
		summarizeBy: none
		sourceColumn: artFrontHorizontal

		annotation SummarizationSetBy = Automatic

	column artBackHorizontal
		dataType: string
		lineageTag: 180a0efd-1869-436c-b211-164751d13254
		summarizeBy: none
		sourceColumn: artBackHorizontal

		annotation SummarizationSetBy = Automatic

	column hasFoil
		dataType: string
		lineageTag: 49cdd285-f883-43e9-a8d0-c1a5e0760d56
		summarizeBy: none
		sourceColumn: hasFoil

		annotation SummarizationSetBy = Automatic

	column cost
		dataType: string
		lineageTag: 5ba49645-d99f-4788-9fb1-edb4f9dd03e6
		summarizeBy: none
		sourceColumn: cost

		annotation SummarizationSetBy = Automatic

	column hp
		dataType: string
		lineageTag: 8c211be8-035c-4944-a903-47d8a930bda5
		summarizeBy: none
		sourceColumn: hp

		annotation SummarizationSetBy = Automatic

	column power
		dataType: string
		lineageTag: c6a93a94-6e8c-4db2-96dc-421d1b28cf1b
		summarizeBy: none
		sourceColumn: power

		annotation SummarizationSetBy = Automatic

	column text
		dataType: string
		lineageTag: f68b89e9-ad7a-4857-9f34-9aab7f01e0c4
		summarizeBy: none
		sourceColumn: text

		annotation SummarizationSetBy = Automatic

	column textStyled
		dataType: string
		lineageTag: 778e800a-c60a-44f8-b32a-932b37812d7a
		summarizeBy: none
		sourceColumn: textStyled

		annotation SummarizationSetBy = Automatic

	column deployBox
		dataType: string
		lineageTag: 334aa5a4-d288-4c3f-a2ed-f79535a686b0
		summarizeBy: none
		sourceColumn: deployBox

		annotation SummarizationSetBy = Automatic

	column deployBoxStyled
		dataType: string
		lineageTag: aad81ffc-16a7-4b97-b06a-f4c607c04e5d
		summarizeBy: none
		sourceColumn: deployBoxStyled

		annotation SummarizationSetBy = Automatic

	column epicAction
		dataType: string
		lineageTag: 76d5e2d9-b2aa-4ea2-ac63-56b083c68942
		summarizeBy: none
		sourceColumn: epicAction

		annotation SummarizationSetBy = Automatic

	column epicActionStyled
		dataType: string
		lineageTag: 390e3082-59cd-465d-8afb-08f7b34960e5
		summarizeBy: none
		sourceColumn: epicActionStyled

		annotation SummarizationSetBy = Automatic

	column linkHtml
		dataType: string
		lineageTag: d918ca8e-07ff-48f6-aa77-fefa65716022
		summarizeBy: none
		sourceColumn: linkHtml

		annotation SummarizationSetBy = Automatic

	column cardId
		dataType: string
		lineageTag: c789ec23-d8e2-4a8f-9dab-028d84ac9df8
		summarizeBy: none
		sourceColumn: cardId

		annotation SummarizationSetBy = Automatic

	column createdAt
		dataType: string
		lineageTag: 9bb25f45-1c43-47e6-a106-c8bb0977c35e
		summarizeBy: none
		sourceColumn: createdAt

		annotation SummarizationSetBy = Automatic

	column updatedAt
		dataType: string
		lineageTag: 53779784-d6e0-497b-bff0-561d1b8cc01a
		summarizeBy: none
		sourceColumn: updatedAt

		annotation SummarizationSetBy = Automatic

	column publishedAt
		dataType: string
		lineageTag: dc55a010-ccca-4e4f-b593-563be9d4b621
		summarizeBy: none
		sourceColumn: publishedAt

		annotation SummarizationSetBy = Automatic

	column locale
		dataType: string
		lineageTag: 9afa9266-6af8-47a1-8b4c-544003ad9570
		summarizeBy: none
		sourceColumn: locale

		annotation SummarizationSetBy = Automatic

	column hyperspace
		dataType: string
		lineageTag: 7c93c9c5-eb67-4295-b57e-d96e5c9912f9
		summarizeBy: none
		sourceColumn: hyperspace

		annotation SummarizationSetBy = Automatic

	column unique
		dataType: string
		lineageTag: 4cdcd7dc-5165-4e15-8815-4a8c5ddaa7c0
		summarizeBy: none
		sourceColumn: unique

		annotation SummarizationSetBy = Automatic

	column showcase
		dataType: string
		lineageTag: bb978ee7-e4c3-4935-a1bf-54455038147a
		summarizeBy: none
		sourceColumn: showcase

		annotation SummarizationSetBy = Automatic

	column cardUid
		dataType: string
		lineageTag: 6f7a54a4-4816-41be-9f3e-11f8d1e7c7c0
		summarizeBy: none
		sourceColumn: cardUid

		annotation SummarizationSetBy = Automatic

	column rules
		dataType: string
		lineageTag: 29cda992-66ef-4597-b96d-e1efcc876066
		summarizeBy: none
		sourceColumn: rules

		annotation SummarizationSetBy = Automatic

	column rulesStyled
		dataType: string
		lineageTag: af724107-2bec-4802-b4ba-3d36475d006f
		summarizeBy: none
		sourceColumn: rulesStyled

		annotation SummarizationSetBy = Automatic

	column serialCode
		dataType: string
		lineageTag: e176e74f-612c-4f33-9915-8574b0813274
		summarizeBy: none
		sourceColumn: serialCode

		annotation SummarizationSetBy = Automatic

	column upgradeHp
		dataType: string
		lineageTag: ea0090ba-15a6-4bf3-86cf-7acd29ba05cc
		summarizeBy: none
		sourceColumn: upgradeHp

		annotation SummarizationSetBy = Automatic

	column upgradePower
		dataType: string
		lineageTag: 0ffe306f-fb03-4024-a6a9-03c98b610a7f
		summarizeBy: none
		sourceColumn: upgradePower

		annotation SummarizationSetBy = Automatic

	column artFront
		dataType: string
		lineageTag: e316197c-0d78-4f8d-8d7c-d36b4a7aa6ad
		summarizeBy: none
		sourceColumn: artFront

		annotation SummarizationSetBy = Automatic

	column artBack
		dataType: string
		lineageTag: ccf475a1-3cc8-4e87-b3d9-b18de4b8c6aa
		summarizeBy: none
		sourceColumn: artBack

		annotation SummarizationSetBy = Automatic

	column artThumbnail
		dataType: string
		lineageTag: 18560a80-b044-4aaf-8b3e-568ce9923ae7
		summarizeBy: none
		sourceColumn: artThumbnail

		annotation SummarizationSetBy = Automatic

	column localizations
		dataType: string
		lineageTag: 7bda6755-ecf1-415d-ad6b-8237209badca
		summarizeBy: none
		sourceColumn: localizations

		annotation SummarizationSetBy = Automatic

	column aspects
		dataType: string
		lineageTag: 26c571ae-6601-41eb-921d-42dc3b2b2d7c
		summarizeBy: none
		sourceColumn: aspects

		annotation SummarizationSetBy = Automatic

	column aspectDuplicates
		dataType: string
		lineageTag: 416d9ac3-064a-41c0-9f00-69c97a0ebd61
		summarizeBy: none
		sourceColumn: aspectDuplicates

		annotation SummarizationSetBy = Automatic

	column 'type.data.attributes.name'
		dataType: string
		lineageTag: 8aa9a85e-6dc3-40b6-98d1-4c57f7edbf15
		summarizeBy: none
		sourceColumn: type.data.attributes.name

		annotation SummarizationSetBy = Automatic

	column type2
		dataType: string
		lineageTag: 0804d4d0-01f2-4937-ab37-c99e1274bc55
		summarizeBy: none
		sourceColumn: type2

		annotation SummarizationSetBy = Automatic

	column traits
		dataType: string
		lineageTag: 75be0bc4-c504-4563-b05d-b90192d2ba50
		summarizeBy: none
		sourceColumn: traits

		annotation SummarizationSetBy = Automatic

	column arenas
		dataType: string
		lineageTag: 816d0675-4f0e-45bd-a5f4-055b3c1bea27
		summarizeBy: none
		sourceColumn: arenas

		annotation SummarizationSetBy = Automatic

	column keywords
		dataType: string
		lineageTag: ef8d0a91-6588-4b79-bd1b-cdf8c0297f1b
		summarizeBy: none
		sourceColumn: keywords

		annotation SummarizationSetBy = Automatic

	column rarity
		dataType: string
		lineageTag: 17232c44-4a57-4bb5-96ad-02a8ba854f06
		summarizeBy: none
		sourceColumn: rarity

		annotation SummarizationSetBy = Automatic

	column expansion
		dataType: string
		lineageTag: 6d02d67c-129e-4719-a0f0-acdb22073956
		summarizeBy: none
		sourceColumn: expansion

		annotation SummarizationSetBy = Automatic

	column variantTypes
		dataType: string
		lineageTag: 4edaafde-3dd7-4fdf-bb4e-ce9b360480c0
		summarizeBy: none
		sourceColumn: variantTypes

		annotation SummarizationSetBy = Automatic

	column variantOf
		dataType: string
		lineageTag: 2457212b-d201-4dfe-b80c-9b71d5256101
		summarizeBy: none
		sourceColumn: variantOf

		annotation SummarizationSetBy = Automatic

	column reprintOf
		dataType: string
		lineageTag: 0a35d55f-836f-4a5f-ae63-a64abb4ea3ec
		summarizeBy: none
		sourceColumn: reprintOf

		annotation SummarizationSetBy = Automatic

	column validationId
		dataType: string
		lineageTag: 19483f45-6655-428b-a7b8-9281290ca9a9
		summarizeBy: none
		sourceColumn: validationId

		annotation SummarizationSetBy = Automatic

	partition Base = m
		mode: import
		queryGroup: 'API Tables'
		source =
				let
				    Source = List.Generate(
				        () => [Result = try GetSWUAPIPages(1) otherwise null, pagenumber=1],
				        each List.IsEmpty([Result]) = false,
				        each [Result = try GetSWUAPIPages(pagenumber) otherwise null, pagenumber = [pagenumber] + 1],
				        each [Result]),
				    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Expanded Column1" = Table.ExpandListColumn(#"Converted to Table", "Column1"),
				    #"Expanded Column2" = Table.ExpandRecordColumn(#"Expanded Column1", "Column1", {"id", "attributes"}, {"id", "attributes"}),
				    #"Expanded attributes" = Table.ExpandRecordColumn(#"Expanded Column2", "attributes", {"title", "subtitle", "cardNumber", "cardCount", "artist", "artFrontHorizontal", "artBackHorizontal", "hasFoil", "cost", "hp", "power", "text", "textStyled", "deployBox", "deployBoxStyled", "epicAction", "epicActionStyled", "linkHtml", "cardId", "createdAt", "updatedAt", "publishedAt", "locale", "hyperspace", "unique", "showcase", "cardUid", "rules", "rulesStyled", "serialCode", "upgradeHp", "upgradePower", "artFront", "artBack", "artThumbnail", "localizations", "aspects", "aspectDuplicates", "type", "type2", "traits", "arenas", "keywords", "rarity", "expansion", "variantTypes", "variantOf", "reprintOf", "validationId"}, {"title", "subtitle", "cardNumber", "cardCount", "artist", "artFrontHorizontal", "artBackHorizontal", "hasFoil", "cost", "hp", "power", "text", "textStyled", "deployBox", "deployBoxStyled", "epicAction", "epicActionStyled", "linkHtml", "cardId", "createdAt", "updatedAt", "publishedAt", "locale", "hyperspace", "unique", "showcase", "cardUid", "rules", "rulesStyled", "serialCode", "upgradeHp", "upgradePower", "artFront", "artBack", "artThumbnail", "localizations", "aspects", "aspectDuplicates", "type", "type2", "traits", "arenas", "keywords", "rarity", "expansion", "variantTypes", "variantOf", "reprintOf", "validationId"}),
				    #"Expanded type" = Table.ExpandRecordColumn(#"Expanded attributes", "type", {"data"}, {"type.data"}),
				    #"Expanded type.data" = Table.ExpandRecordColumn(#"Expanded type", "type.data", {"attributes"}, {"type.data.attributes"}),
				    #"Expanded type.data.attributes" = Table.ExpandRecordColumn(#"Expanded type.data", "type.data.attributes", {"name"}, {"type.data.attributes.name"}),
				    #"Filtered Rows" = Table.SelectRows(#"Expanded type.data.attributes", each not Text.Contains([type.data.attributes.name], "Token"))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

