table Collection
	lineageTag: ec7fc4b2-b3b1-4a40-b396-1e11afe886d3

	column set
		dataType: string
		lineageTag: c42a76c4-7de6-449e-a547-9e90ef2234fa
		summarizeBy: none
		sourceColumn: set

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column owned
		dataType: int64
		formatString: 0
		lineageTag: b62ca42b-a1d4-45b6-9250-398f23695356
		summarizeBy: sum
		sourceColumn: owned

		annotation SummarizationSetBy = Automatic

	column variant
		dataType: string
		lineageTag: af0edb5e-ab24-4e65-8448-5ef8cbdd1094
		summarizeBy: none
		sourceColumn: variant

		annotation SummarizationSetBy = Automatic

	column 'title - subtitle'
		dataType: string
		lineageTag: 45e73b57-ce3a-4ed5-8b2b-b2bf7bbbf954
		summarizeBy: none
		sourceColumn: title - subtitle

		annotation SummarizationSetBy = Automatic

	column standardKey
		dataType: string
		lineageTag: b72cee8d-2e75-4edf-8d71-2daa6c1b0267
		summarizeBy: none
		sourceColumn: standardKey

		annotation SummarizationSetBy = Automatic

	column 'title - sibtitle - set'
		dataType: string
		lineageTag: 9831a7f9-467f-47af-99b3-196c6265ac0e
		summarizeBy: none
		sourceColumn: title - sibtitle - set

		annotation SummarizationSetBy = Automatic

	column cardUid
		dataType: string
		lineageTag: 6b44c3ee-3e06-4b4e-8c34-0be6bfd68e7e
		summarizeBy: none
		sourceColumn: cardUid

		annotation SummarizationSetBy = Automatic

	column aspect1
		dataType: string
		lineageTag: 30fa293f-2c15-4235-9b01-04a931fc04b9
		summarizeBy: none
		sourceColumn: aspect1

		annotation SummarizationSetBy = Automatic

	column aspect2
		dataType: string
		lineageTag: 6e63db4a-f797-43af-9015-243c1f0a9733
		summarizeBy: none
		sourceColumn: aspect2

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: 381120dd-8d95-4160-8064-df86cf9f5459
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	partition Collection = m
		mode: import
		queryGroup: 'Folder Tables'
		source =
				let
				    Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1ymASHx_Tr96ny7D32RozMHar14Bde2wRLNIRAaOMiv8/edit?gid=1884736088#gid=1884736088"),
				    cards_Sheet = Source{[name="PBIOutput",ItemKind="Table"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(cards_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"title - subtitle", type text}, {"cardUid", type text}, {"variant", type text}, {"standardKey", type text}, {"owned", Int64.Type}, {"aspect1", type text}, {"aspect2", type text}, {"type", type text}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "title - sibtitle - set", each [#"title - subtitle"] & " - " & [set]),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Custom", each Text.PadStart(Text.From([cardUid]), 10, "0")),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Custom1",{"cardUid"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Custom", "cardUid"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

