table Decks
	lineageTag: 2a4d3154-213d-47f6-9381-704ff364ab0d

	column 'Source.Name'
		dataType: string
		lineageTag: dd405a69-167b-439f-af8f-846947d6d1b4
		summarizeBy: none
		sourceColumn: Source.Name

		annotation SummarizationSetBy = Automatic

	column 'metadata.name'
		dataType: string
		lineageTag: a2fd92f6-aee7-48a7-8df1-1f13ace09f35
		summarizeBy: none
		sourceColumn: metadata.name

		annotation SummarizationSetBy = Automatic

	column 'metadata.author'
		dataType: string
		lineageTag: dfe50653-c365-46dc-bf50-fc6646f12979
		summarizeBy: none
		sourceColumn: metadata.author

		annotation SummarizationSetBy = Automatic

	column 'Card Type'
		dataType: string
		lineageTag: fb00653d-023a-47f0-99dd-1c58dba25657
		summarizeBy: none
		sourceColumn: Card Type
		sortByColumn: cardtypeSort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Card ID'
		dataType: string
		lineageTag: 3258b532-ad10-4c5f-9b5b-b4aeef1e01aa
		summarizeBy: none
		sourceColumn: Card ID

		annotation SummarizationSetBy = Automatic

	column 'Card Count'
		dataType: int64
		formatString: 0
		lineageTag: 6268da33-92bb-4336-bd87-98e53ea1a45d
		summarizeBy: sum
		sourceColumn: Card Count

		annotation SummarizationSetBy = Automatic

	column cardtypeSort
		dataType: string
		lineageTag: 912ab92e-c576-45b0-b1fd-71a8a1658e04
		summarizeBy: none
		sourceColumn: cardtypeSort

		annotation SummarizationSetBy = Automatic

	partition Decks = m
		mode: import
		queryGroup: 'Folder Tables'
		source =
				let
				    Source = Table.Combine({Maindeck, Sideboards}),
				    AddIndex = Table.AddIndexColumn(Source, "RowID", 0, 1, Int64.Type),
				
				    // Unpivot ID columns
				    UnpivotIDs = Table.UnpivotOtherColumns(AddIndex, {"RowID", "metadata.name", "metadata.author", "Source.Name"}, "Attribute", "Card ID"),
				    FilterIDs = Table.SelectRows(UnpivotIDs, each Text.EndsWith([Attribute], ".id")),
				    AddType = Table.TransformColumns(FilterIDs, {{"Attribute", each Text.BeforeDelimiter(_, "."), type text}}),
				
				    // Unpivot Count columns
				    UnpivotCounts = Table.UnpivotOtherColumns(AddIndex, {"RowID", "metadata.name", "metadata.author", "Source.Name"}, "Attribute", "Card Count"),
				    FilterCounts = Table.SelectRows(UnpivotCounts, each Text.EndsWith([Attribute], ".count")),
				    AddTypeCount = Table.TransformColumns(FilterCounts, {{"Attribute", each Text.BeforeDelimiter(_, "."), type text}}),
				
				    // Join ID + Count on RowID and Card Type
				    Merged = Table.NestedJoin(AddType, {"RowID", "Attribute"}, AddTypeCount, {"RowID", "Attribute"}, "JoinedCounts"),
				    Expanded = Table.ExpandTableColumn(Merged, "JoinedCounts", {"Card Count"}),
				
				    // Clean up
				    RemovedColumns = Table.RemoveColumns(Expanded, {"RowID"}),
				    Renamed = Table.RenameColumns(RemovedColumns, {{"Attribute", "Card Type"}}),
				    #"Removed Duplicates" = Table.Distinct(Renamed),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Duplicates",{{"Card Count", Int64.Type}, {"Card ID", type text}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Changed Type", "cardtypeSort", each if [Card Type] = "leader" then 1 else if [Card Type] = "base" then 2 else if [Card Type] = "deck" then 3 else if [Card Type] = "sideboard" then 4 else null)
				in
				    #"Added Conditional Column"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

