table 'Measure Table'
	lineageTag: 36844c73-a776-467d-abf1-c500aad03540

	measure 'Card Count - Distinct' = DISTINCTCOUNTNOBLANK(Cards[title + subtitle])
		formatString: 0
		lineageTag: 8d030d25-0fc2-467d-9289-225ddf30118f

	measure 'Card Count - All Variants' = DISTINCTCOUNT(Cards[cardUid])
		formatString: 0
		lineageTag: 4f9fa2ea-5f45-4f52-abc1-a91026a92d9c

	measure 'Card Count - Set' = DISTINCTCOUNTNOBLANK(Cards[title + subtitle + set])
		formatString: 0
		lineageTag: 33601163-1f04-4877-8efb-6c42b6333104

	measure 'Rulings Check' = IF(ISBLANK(MAX(Rules[ruling])), "No additional rulings available for this card", BLANK())
		lineageTag: ff25b9f0-6246-485e-a5b3-510122291b07

	measure 'Card Image Switcher' =
			
			VAR SelectedFrontImage = SELECTEDVALUE(Cards[artFront.data.attributes.url])
			VAR SelectedBackImage = SELECTEDVALUE(Cards[artBack.data.attributes.url.cardBack])
			VAR HoverChoice = SELECTEDVALUE(HoverSelector[View], "Front")
			
			RETURN
			IF(HoverChoice = "Front", SelectedFrontImage, SelectedBackImage)
		lineageTag: 76d97ae8-545b-4e09-ad04-469a9ed54a36
		dataCategory: ImageUrl

	measure 'Trade Value A' =
			
			CALCULATE(
			    IF(ISBLANK(SUM(Pricing[marketPrice])), SUM(Pricing[midPrice]), SUM(Pricing[marketPrice])),
			    TREATAS(VALUES(TradeSideA[Title]), Cards[Title]),
			    TREATAS(VALUES(TradeSideA[Subtitle]), Cards[Subtitle]),
			    TREATAS(VALUES(TradeSideA[Variant]), Variants[name])
			) * 'Trade %'[Trade % Value]
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 7867d447-85ee-4f1f-ab6e-1815ad857ff5

	measure 'Trade Value B' =
			
			CALCULATE(
			    IF(ISBLANK(SUM(Pricing[marketPrice])), SUM(Pricing[midPrice]), SUM(Pricing[marketPrice])),
			    TREATAS(VALUES(TradeSideB[Title]), Cards[Title]),
			    TREATAS(VALUES(TradeSideB[Subtitle]), Cards[Subtitle]),
			    TREATAS(VALUES(TradeSideB[Variant]), Variants[name])
			) * 'Trade %'[Trade % Value]
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 53f27732-3830-4f72-9fad-f34b04e68334

	measure 'Trade Value Difference' = [Trade Value A] - [Trade Value B]
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: eed17964-14c1-4729-afe4-4fb4bccdb058

	measure 'Card Count' =
			
			SUMX(
			    DISTINCT('Cards Fact'[expansion.data.id]),
			    SWITCH(
			        TRUE(),
			        'Cards Fact'[expansion.data.id] = "13", 6,
			        'Cards Fact'[expansion.data.id] = "28", 6,
			        'Cards Fact'[expansion.data.id] = "43", 4,
			        'Cards Fact'[expansion.data.id] = "48", 20,
			        CALCULATE(
			            MAX('Cards'[cardCount]),
			            'Cards Fact'[expansion.data.id] = EARLIER('Cards Fact'[expansion.data.id])
			        )
			    )
			)
		formatString: 0
		lineageTag: 102f46d6-646a-44dc-8413-f07dab17c1f3

	measure 'Variant Count' = ```
			
			SUMX(
			    SUMMARIZE(
			        'Cards Fact', 
			        'Cards Fact'[expansion.data.id], 
			        'Cards Fact'[cardUid],  -- Assuming CardID exists in the Cards Fact table
			        "DistinctVariants", DISTINCTCOUNT('Variants'[id])
			    ),
			    [DistinctVariants]
			)
			```
		formatString: 0
		lineageTag: b3c865e9-7747-4e31-97ca-c4ead591a005

	measure 'Random Card' =
			
			CALCULATE(
			    MAX(Cards[artFront.data.attributes.url]),
			    SAMPLE(1, Cards, RAND())
			)
		lineageTag: 49a8956a-beb0-41e5-90d2-204984d1036f
		dataCategory: ImageUrl

	measure 'Price Target' =
			
			SWITCH(
			    TRUE(),
			    SELECTEDVALUE(Cards[rarity.data.attributes.name]) = "Legendary" && SELECTEDVALUE(Pricing[marketPrice]) <= 'Legendary Price Target'[Legendary Price Target Value], "#34d14b",
			    SELECTEDVALUE(Cards[rarity.data.attributes.name]) = "Rare" && SELECTEDVALUE(Pricing[marketPrice]) <= 'Rare Price Target'[Rare Price Target Value], "#34d14b"
			)
		lineageTag: 18b73e25-4909-42f2-9a28-762b860214fd

	column Column
		isHidden
		formatString: 0
		lineageTag: 0d4347ed-8fbb-4801-9614-d27c9779739e
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition 'Measure Table' = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = b74392a275e94050a0d8fa80c9e5c0af

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

