table 'Measure Table'
	lineageTag: 36844c73-a776-467d-abf1-c500aad03540

	measure 'Card Count - Distinct' = DISTINCTCOUNTNOBLANK(Cards[title + subtitle])
		formatString: 0
		lineageTag: 8d030d25-0fc2-467d-9289-225ddf30118f

	measure 'Card Count - All Variants' = DISTINCTCOUNT(Cards[cardUid])
		formatString: 0
		lineageTag: 4f9fa2ea-5f45-4f52-abc1-a91026a92d9c

	measure 'Card Count - Set' = DISTINCTCOUNTNOBLANK(Cards[title + subtitle + set])
		formatString: 0
		lineageTag: 33601163-1f04-4877-8efb-6c42b6333104

	measure 'Rulings Check' = IF(ISBLANK(MAX(Rules[ruling])), "No additional rulings available for this card", BLANK())
		lineageTag: ff25b9f0-6246-485e-a5b3-510122291b07

	measure 'Card Image Switcher' =
			
			VAR SelectedFrontImage = SELECTEDVALUE(Cards[artFront.data.attributes.url])
			VAR SelectedBackImage = SELECTEDVALUE(Cards[artBack.data.attributes.url.cardBack])
			VAR HoverChoice = SELECTEDVALUE(HoverSelector[View], "Front")
			
			RETURN
			IF(HoverChoice = "Front", SelectedFrontImage, SelectedBackImage)
		lineageTag: 76d97ae8-545b-4e09-ad04-469a9ed54a36
		dataCategory: ImageUrl

	measure 'Owned - Hyperspace' =
			
			CALCULATE(
			    SUM(Collection[owned]),
			    Variants[id] = "56"
			)
		formatString: 0
		lineageTag: f3a7ddb5-1621-4252-9592-8e897d2f6a08

	measure 'Owned - Convention Exclusive' =
			
			CALCULATE(
			    SUM(Collection[owned]),
			    Variants[id] = "41"
			)
		formatString: 0
		lineageTag: df041a8c-11ce-434d-8834-418ed1ad34bc

	measure 'Owned - Event Exclusive' =
			
			CALCULATE(
			    SUM(Collection[owned]),
			    Variants[id] = "2"
			)
		formatString: 0
		lineageTag: ce066233-87eb-40eb-998e-1f094488287d

	measure 'Owned - Prestige Foil' =
			
			CALCULATE(
			    SUM(Collection[owned]),
			    Variants[id] = "86"
			)
		formatString: 0
		lineageTag: 706a8c02-2eaa-4b82-995c-a5da92482596

	measure 'Owned - Hyperfoil' =
			
			CALCULATE(
			    SUM(Collection[owned]),
			    Variants[id] = "61"
			)
		formatString: 0
		lineageTag: 8cb02bb1-d3ed-4e1f-aaec-5e2f85129cab

	measure 'Owned - Judge Program' =
			
			CALCULATE(
			    SUM(Collection[owned]),
			    Variants[id] = "126"
			)
		formatString: 0
		lineageTag: e8371f5a-0ac4-48c0-a5a8-6dd141520963

	measure 'Owned - OP' =
			
			CALCULATE(
			    SUM(Collection[owned]),
			    Variants[id] IN {"36", "31", "16", "1", "71", "26", "21"}
			)
		formatString: 0
		lineageTag: d06fd14f-93bb-4234-9bb5-9df144ca8ad2

	measure 'Owned - Prerelease' =
			
			CALCULATE(
			    SUM(Collection[owned]),
			    Variants[id] = "3"
			)
		formatString: 0
		lineageTag: 713fb791-309e-4300-88a5-f100f280cfe1

	measure 'Owned - Serialized Prestige' =
			
			CALCULATE(
			    SUM(Collection[owned]),
			    Variants[id] = "91"
			)
		formatString: 0
		lineageTag: 99a3a4fc-9f7a-4df5-bf6b-b03b04e4f015

	measure 'Owned - Showcase' =
			
			CALCULATE(
			    SUM(Collection[owned]),
			    Variants[id] = "66"
			)
		formatString: 0
		lineageTag: bc9cf7f5-84f4-487b-b82e-0cdf6d80f739

	measure 'Owned - Standard' =
			
			CALCULATE(
			    SUM(Collection[owned]),
			    Variants[id] = "46"
			)
		formatString: 0
		lineageTag: 86ec251b-9e3a-4116-b94c-702698532be5

	measure 'Owned - Standard Foil' =
			
			CALCULATE(
			    SUM(Collection[owned]),
			    Variants[id] = "51"
			)
		formatString: 0
		lineageTag: f281877b-780c-4951-aaa2-069b5b0af1ad

	measure 'Owned - Prestige' =
			
			CALCULATE(
			    SUM(Collection[owned]),
			    Variants[id] = "81"
			)
		formatString: 0
		lineageTag: 8c6c5a84-56f4-419e-b648-047fdd97722d

	measure Owned = SUM(Collection[owned]) + 0
		formatString: 0
		lineageTag: ae710d14-7053-461f-a3cd-6afedc8ab277

	measure 'Used in Decks' = SUM(Decks[Card Count])
		formatString: 0
		lineageTag: 41b873af-8219-4a88-b7db-f1aad9d6f11b

	measure Available = [Owned] - [Used in Decks]
		formatString: 0
		lineageTag: 0a7c8bc2-8b11-40ed-967e-997cb13bc8a2

	measure 'Collection Value' =
			
			SUMX(
			    VALUES(Collection[cardUid]),
			    CALCULATE(
			        MAX(Collection[owned]) * MAX(Pricing[marketPrice])
			    )
			)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: c11f2f5e-4bf2-47f4-87e2-ed2194d5a418

	measure 'Master Set Completion %' =
			
			DIVIDE(
			    [Distinct Variants Owned],
			    MAX(Collection[cardNumber]) * DISTINCTCOUNT(Variants[name])
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 5412ebf8-bf3f-48cb-869a-de6821aee841

	measure 'Distinct Variants Owned' =
			
			CALCULATE(
			    DISTINCTCOUNT(Collection[id]),
			    Collection[owned] > 0
			)
		formatString: 0
		lineageTag: dde1c3d8-0a63-4c8f-8998-58fc3244c62a

	measure 'Distinct Cards Owned' =
			
			CALCULATE(
			    DISTINCTCOUNT(Collection[title - subtitle]),
			    Collection[owned] > 0
			)
		formatString: 0
		lineageTag: e0bf1009-336c-4b70-aa52-4e8a2cf80f58

	measure 'Set Completion %' =
			
			[Distinct Cards Owned]
			/
			MAX(Collection[cardNumber])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 9848b158-b9b4-4b9d-a73f-5f57984e70e2

	measure 'Completed Playsets' =
			
			CALCULATE(
			    DISTINCTCOUNT(Collection[title - subtitle]),
			    Collection[owned] >= 3
			)
		formatString: 0
		lineageTag: ce98fc4c-5122-436d-8ca8-bf6c138417cb

	measure 'Playset Completion %' =
			
			DIVIDE(
			    [Completed Playsets],
			    MAX(Collection[cardNumber])
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 4c67512e-828c-4418-9de3-4e7be7914347

	measure 'Number of Playsets' =
			
			DIVIDE(
			    [Owned],
			    3
			)
		lineageTag: 34f748c3-052b-416e-bd95-ca3413970bdc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Trade Value A' =
			
			CALCULATE(
			    SUM(Pricing[marketPrice]),
			    TREATAS(VALUES(TradeSideA[Title]), Cards[Title]),
			    TREATAS(VALUES(TradeSideA[Subtitle]), Cards[Subtitle]),
			    TREATAS(VALUES(TradeSideA[Variant]), Variants[name])
			) * 'Trade %'[Trade % Value]
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 7867d447-85ee-4f1f-ab6e-1815ad857ff5

	measure 'Trade Value B' =
			
			CALCULATE(
			    SUM(Pricing[marketPrice]),
			    TREATAS(VALUES(TradeSideB[Title]), Cards[Title]),
			    TREATAS(VALUES(TradeSideB[Subtitle]), Cards[Subtitle]),
			    TREATAS(VALUES(TradeSideB[Variant]), Variants[name])
			) * 'Trade %'[Trade % Value]
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 53f27732-3830-4f72-9fad-f34b04e68334

	measure 'Trade Value Difference' = [Trade Value A] - [Trade Value B]
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: eed17964-14c1-4729-afe4-4fb4bccdb058

	column Column
		isHidden
		formatString: 0
		lineageTag: 0d4347ed-8fbb-4801-9614-d27c9779739e
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition 'Measure Table' = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = b74392a275e94050a0d8fa80c9e5c0af

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

