table 'Meta Stats - Tournament Stats'
	lineageTag: 7af5d070-a974-4cb6-b151-760d76844cd7

	measure 'Number of Rounds' = MAX('Meta Stats - Tournament Stats'[Matches Played]) - 3
		formatString: 0
		lineageTag: 20c5aa0e-2d80-4938-b990-b00e88179a49

	column tourney
		dataType: int64
		formatString: 0
		lineageTag: d4f20c8f-ab0c-441e-8710-4fecab2fd65b
		summarizeBy: none
		sourceColumn: tourney

		annotation SummarizationSetBy = Automatic

	column id
		dataType: int64
		formatString: 0
		lineageTag: f22631ce-d2c1-491e-b63a-8cac3520a3c7
		summarizeBy: sum
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column player
		dataType: string
		lineageTag: 2a4f9287-567d-426c-a77f-6b5689adf991
		summarizeBy: none
		sourceColumn: player

		annotation SummarizationSetBy = Automatic

	column rank
		dataType: int64
		formatString: 0
		lineageTag: 7b7f233c-db16-45a3-8c75-62363ddf935c
		summarizeBy: sum
		sourceColumn: rank

		annotation SummarizationSetBy = Automatic

	column match_record
		dataType: string
		lineageTag: b7dcc2cd-dcf8-4fb7-aea3-378cdfa14750
		summarizeBy: none
		sourceColumn: match_record

		annotation SummarizationSetBy = Automatic

	column match_wins
		dataType: int64
		formatString: 0
		lineageTag: a95658ed-eac7-4859-99a1-973fb7fdcab9
		summarizeBy: sum
		sourceColumn: match_wins

		annotation SummarizationSetBy = Automatic

	column match_losses
		dataType: int64
		formatString: 0
		lineageTag: cc37afde-847f-40af-a880-2a9966106d8c
		summarizeBy: sum
		sourceColumn: match_losses

		annotation SummarizationSetBy = Automatic

	column match_draws
		dataType: int64
		formatString: 0
		lineageTag: 6d764c53-64b4-4c27-afe9-f9534a6e7948
		summarizeBy: sum
		sourceColumn: match_draws

		annotation SummarizationSetBy = Automatic

	column match_win_rate
		dataType: double
		formatString: 0.00
		lineageTag: 71dfe2b1-41e6-4550-a8ad-5ccafb0f86a2
		summarizeBy: average
		sourceColumn: match_win_rate

		annotation SummarizationSetBy = User

	column game_record
		dataType: string
		lineageTag: 465333d1-62ef-4750-a216-d6b52caa477c
		summarizeBy: none
		sourceColumn: game_record

		annotation SummarizationSetBy = Automatic

	column game_wins
		dataType: int64
		formatString: 0
		lineageTag: d94e7d08-89ca-4e7b-890e-bb8f2acf0d2d
		summarizeBy: sum
		sourceColumn: game_wins

		annotation SummarizationSetBy = Automatic

	column game_losses
		dataType: int64
		formatString: 0
		lineageTag: e24b75bc-2976-4647-b88b-d8c062688788
		summarizeBy: sum
		sourceColumn: game_losses

		annotation SummarizationSetBy = Automatic

	column game_draws
		dataType: int64
		formatString: 0
		lineageTag: c99e0593-e6f2-4fbe-a080-06b3ad1b0508
		summarizeBy: sum
		sourceColumn: game_draws

		annotation SummarizationSetBy = Automatic

	column game_win_rate
		dataType: double
		formatString: 0.00
		lineageTag: fb2b3b8b-ce7a-4ea7-a56a-a0c2823ecbb5
		summarizeBy: average
		sourceColumn: game_win_rate

		annotation SummarizationSetBy = User

	column points
		dataType: int64
		formatString: 0
		lineageTag: 51e1a68e-6857-43c9-bcfa-b62e19976b35
		summarizeBy: sum
		sourceColumn: points

		annotation SummarizationSetBy = Automatic

	column omwp
		dataType: double
		lineageTag: e5088241-b924-42de-8886-6c4659987661
		summarizeBy: sum
		sourceColumn: omwp

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column tgwp
		dataType: double
		lineageTag: d3607233-04a0-4211-9a25-696afd42fd83
		summarizeBy: sum
		sourceColumn: tgwp

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ogwp
		dataType: double
		lineageTag: 040d1d34-df43-49c3-b1e1-c879965bc5f1
		summarizeBy: sum
		sourceColumn: ogwp

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'leader.uuid'
		dataType: string
		lineageTag: a447cde5-c333-4487-90a6-990ad5e1c47c
		summarizeBy: none
		sourceColumn: leader.uuid

		annotation SummarizationSetBy = Automatic

	column 'base.uuid'
		dataType: string
		lineageTag: 6303aba6-edfa-4422-9a9e-01aacb62dd15
		summarizeBy: none
		sourceColumn: base.uuid

		annotation SummarizationSetBy = Automatic

	column 'Matches Played' = 'Meta Stats - Tournament Stats'[match_draws] + 'Meta Stats - Tournament Stats'[match_losses] + 'Meta Stats - Tournament Stats'[match_wins]
		formatString: 0
		lineageTag: e68fc3fa-6678-4d20-9daf-0bff8b02ebdf
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'All Rounds Played' = ```
			IF('Meta Stats - Tournament Stats'[Matches Played] >= [Number of Rounds], 1, 0) 
			```
		formatString: 0
		lineageTag: a0765dfe-140b-47a7-9ece-d3dcdf96104a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition 'Meta Stats - Tournament Stats' = m
		mode: import
		queryGroup: 'SWU Stats Tables'
		source = ```
				let
				    // Reference your Groups table
				    tourneyTable = #"Meta Stats - Tournaments",
				
				    // Get just the groupId column as a list
				    tourneyIds = tourneyTable[id],
				
				    // Call the function for each groupId
				    results = List.Transform(tourneyIds, each 
				        [ 
				            tourney = _, 
				            data = try GetSWUTourneys(_) otherwise null
				        ]
				    ),
				    #"Converted to Table" = Table.FromList(results, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Expanded Column1" = Table.ExpandRecordColumn(#"Converted to Table", "Column1", {"tourney", "data"}, {"tourney", "data"}),
				    #"Expanded data" = Table.ExpandTableColumn(#"Expanded Column1", "data", {"id", "player", "leader", "base", "rank", "standings", "points", "tiebreakers"}, {"id", "player", "leader", "base", "rank", "standings", "points", "tiebreakers"}),
				    #"Expanded leader" = Table.ExpandRecordColumn(#"Expanded data", "leader", {"uuid"}, {"leader.uuid"}),
				    #"Expanded base" = Table.ExpandRecordColumn(#"Expanded leader", "base", {"uuid"}, {"base.uuid"}),
				    #"Expanded standings" = Table.ExpandRecordColumn(#"Expanded base", "standings", {"match_record", "match_wins", "match_losses", "match_draws", "match_win_rate", "game_record", "game_wins", "game_losses", "game_draws", "game_win_rate"}, {"match_record", "match_wins", "match_losses", "match_draws", "match_win_rate", "game_record", "game_wins", "game_losses", "game_draws", "game_win_rate"}),
				    #"Expanded tiebreakers" = Table.ExpandRecordColumn(#"Expanded standings", "tiebreakers", {"omwp", "tgwp", "ogwp"}, {"omwp", "tgwp", "ogwp"}),
				    #"Added Custom" = Table.AddColumn(#"Expanded tiebreakers", "leader.uuid.1", each Text.PadStart(Text.From([leader.uuid]), 10, "0")),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "base.uuid.1", each Text.PadStart(Text.From([base.uuid]), 10, "0")),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Custom1",{"leader.uuid", "base.uuid"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"leader.uuid.1", "leader.uuid"}, {"base.uuid.1", "base.uuid"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"tourney", Int64.Type}, {"id", Int64.Type}, {"player", type text}, {"rank", Int64.Type}, {"match_record", type text}, {"match_wins", Int64.Type}, {"match_losses", Int64.Type}, {"match_draws", Int64.Type}, {"match_win_rate", type number}, {"game_record", type text}, {"game_wins", Int64.Type}, {"game_losses", Int64.Type}, {"game_draws", Int64.Type}, {"game_win_rate", type number}, {"points", Int64.Type}, {"omwp", type number}, {"tgwp", type number}, {"ogwp", type number}})
				in
				    #"Changed Type"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

