table 'Meta Stats - Card'
	lineageTag: fdd29426-7f59-4199-bee9-e3d485c5dfac

	column cardUid
		dataType: int64
		formatString: 0
		lineageTag: 5bd0972e-0dc5-4d7e-9d60-a006cb65e783
		summarizeBy: sum
		sourceColumn: cardUid

		annotation SummarizationSetBy = Automatic

	column cardName
		dataType: string
		lineageTag: 7a5a6ebb-f742-47e4-afb1-f8303fcf328b
		summarizeBy: none
		sourceColumn: cardName

		annotation SummarizationSetBy = Automatic

	column week
		dataType: int64
		formatString: 0
		lineageTag: f5d46ca3-083a-4d6a-9c40-247d3cc5f991
		summarizeBy: sum
		sourceColumn: week

		annotation SummarizationSetBy = Automatic

	column timesIncluded
		dataType: int64
		formatString: 0
		lineageTag: 1f047383-8938-4f0b-a38d-77097fb71822
		summarizeBy: sum
		sourceColumn: timesIncluded

		annotation SummarizationSetBy = Automatic

	column timesIncludedInWins
		dataType: int64
		formatString: 0
		lineageTag: 9ad3125e-19ac-4a19-827d-03d85217e81a
		summarizeBy: sum
		sourceColumn: timesIncludedInWins

		annotation SummarizationSetBy = Automatic

	column percentIncludedInWins
		dataType: double
		lineageTag: 4e10fbb2-8619-404a-a142-ee3957621023
		summarizeBy: sum
		sourceColumn: percentIncludedInWins

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column timesPlayed
		dataType: int64
		formatString: 0
		lineageTag: c0c654c3-056a-4d76-9628-d8ea0afe298f
		summarizeBy: sum
		sourceColumn: timesPlayed

		annotation SummarizationSetBy = Automatic

	column timesPlayedInWins
		dataType: int64
		formatString: 0
		lineageTag: b296c35f-a0c6-4e17-90c6-2c8778f905e5
		summarizeBy: sum
		sourceColumn: timesPlayedInWins

		annotation SummarizationSetBy = Automatic

	column percentPlayedInWins
		dataType: double
		lineageTag: 118582f2-d71a-4802-abe4-bede58f56668
		summarizeBy: sum
		sourceColumn: percentPlayedInWins

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column timesResourced
		dataType: int64
		formatString: 0
		lineageTag: 1e885b57-0b89-42e9-b415-2669b7d5a2ce
		summarizeBy: sum
		sourceColumn: timesResourced

		annotation SummarizationSetBy = Automatic

	column timesResourcedInWins
		dataType: int64
		formatString: 0
		lineageTag: 5db426dd-0f94-431b-beba-94e3e7aa9ac9
		summarizeBy: sum
		sourceColumn: timesResourcedInWins

		annotation SummarizationSetBy = Automatic

	column percentResourcedInWins
		dataType: double
		lineageTag: 2b48c428-977d-4402-a319-d63ef059ba3b
		summarizeBy: sum
		sourceColumn: percentResourcedInWins

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cardUID2
		dataType: string
		lineageTag: 070363ad-8ced-4f8c-b5ac-1cbf1574655a
		summarizeBy: none
		sourceColumn: cardUID2

		annotation SummarizationSetBy = Automatic

	partition 'Meta Stats - Card' = m
		mode: import
		queryGroup: 'SWU Stats Tables'
		source =
				let
				    Source = Json.Document(Web.Contents("https://swustats.net/TCGEngine/Stats/CardMetaStatsAPI.php")),
				    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Expanded Column1" = Table.ExpandRecordColumn(#"Converted to Table", "Column1", {"cardUid", "cardName", "week", "timesIncluded", "timesIncludedInWins", "percentIncludedInWins", "timesPlayed", "timesPlayedInWins", "percentPlayedInWins", "timesResourced", "timesResourcedInWins", "percentResourcedInWins"}, {"cardUid", "cardName", "week", "timesIncluded", "timesIncludedInWins", "percentIncludedInWins", "timesPlayed", "timesPlayedInWins", "percentPlayedInWins", "timesResourced", "timesResourcedInWins", "percentResourcedInWins"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Column1",{{"cardUid", Int64.Type}, {"cardName", type text}, {"week", Int64.Type}, {"timesIncluded", Int64.Type}, {"timesIncludedInWins", Int64.Type}, {"percentIncludedInWins", type number}, {"timesPlayed", Int64.Type}, {"timesPlayedInWins", Int64.Type}, {"percentPlayedInWins", type number}, {"timesResourced", Int64.Type}, {"timesResourcedInWins", Int64.Type}, {"percentResourcedInWins", type number}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "cardUID2", each Text.PadStart(Text.From([cardUid]), 10, "0"))
				in
				    #"Added Custom"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

