table 'Pricing Bridge'
	lineageTag: a85fec7b-8021-4460-a95f-07a38fb8c114

	column cardNumber
		dataType: int64
		formatString: 0
		lineageTag: 306d6fc0-707c-4dc8-a317-4d13a90edf1e
		summarizeBy: sum
		sourceColumn: cardNumber

		annotation SummarizationSetBy = Automatic

	column cardCount
		dataType: int64
		formatString: 0
		lineageTag: 549856f7-b69d-4c04-a34e-e46a464e0b0f
		summarizeBy: sum
		sourceColumn: cardCount

		annotation SummarizationSetBy = Automatic

	column cardUid
		dataType: string
		lineageTag: 4394f872-36f3-4154-9f25-392d8cd66f49
		summarizeBy: none
		sourceColumn: cardUid

		annotation SummarizationSetBy = Automatic

	column 'expansion.data.id'
		dataType: string
		lineageTag: c5fd92d2-d979-4a93-88ea-88236770b340
		summarizeBy: none
		sourceColumn: expansion.data.id

		annotation SummarizationSetBy = Automatic

	column 'expansion.data.attributes.code'
		dataType: string
		lineageTag: 1f14d585-cc34-4e1f-9861-3e64911fdf3d
		summarizeBy: none
		sourceColumn: expansion.data.attributes.code

		annotation SummarizationSetBy = Automatic

	column 'variantTypes.data.id'
		dataType: string
		lineageTag: e6e11d81-aedb-455f-80b6-d7854d56643d
		summarizeBy: none
		sourceColumn: variantTypes.data.id

		annotation SummarizationSetBy = Automatic

	column 'variantTypes.data.attributes.name'
		dataType: string
		lineageTag: 1b65df67-2693-482c-bc45-8c6436d4db08
		summarizeBy: none
		sourceColumn: variantTypes.data.attributes.name

		annotation SummarizationSetBy = Automatic

	column priceKey = ```
			
			//Prefix
			SWITCH(
			    TRUE(),
			    'Pricing Bridge'[id] IN {"8667", "8672", "8677", "8682", "8687", "8692", "8697", "8702", "2668", "1828", "2673", "1969", "2681", "1739", "1818", "2659", "15614", "15618", "15622", "15626", "15630", "15634", "15638", "15642"}, LEFT('Pricing Bridge'[expansion.data.attributes.code], 3) & "-WPP",
			    'Pricing Bridge'[id] IN {"981", "982"}, "EEP",
			    'Pricing Bridge'[id] IN {"8664", "8834", "19456", "19461"}, "PRE",
			    'Pricing Bridge'[id] IN {"8712", "19466", "1015", "16960", "16964"}, "SSP",
			    OR(ISBLANK('Pricing Bridge'[variantTypes.data.attributes.name]), 'Pricing Bridge'[variantTypes.data.attributes.name] IN {"OP Promo", "OP Promo Foil", ""}), LEFT('Pricing Bridge'[expansion.data.attributes.code], 3) & "-WPP",
			    'Pricing Bridge'[variantTypes.data.attributes.name] IN {"OP Judge", "Judge Program"}, "JDG",
			    'Pricing Bridge'[variantTypes.data.attributes.name] = "Prerelease Promo", "PRE",
			    'Pricing Bridge'[variantTypes.data.attributes.name] = "Convention Exclusive", "CE2024",
			    'Pricing Bridge'[variantTypes.data.attributes.name] = "Event Exclusive", "EEP",
			    'Pricing Bridge'[variantTypes.data.attributes.name] IN {"OP Champion", "OP Finalist", "OP Top 4", "OP Top 8", "OP Top 16"}, "SSP",
			    'Pricing Bridge'[expansion.data.attributes.code]
			) 
			& "_" &
			//CardNumber
			SWITCH(
			    TRUE(),
			    'Pricing Bridge'[id] IN {"8667", "8672", "8677", "8682", "8687", "8692", "8697", "8702", "2668", "1828", "2673", "1969", "2681", "1739", "1818", "2659", "15614", "15618", "15622", "15626", "15630", "15634", "15638", "15642"}, FORMAT('Pricing Bridge'[cardNumber], "00"),
			    'Pricing Bridge'[id] IN {"981", "982"}, 'Pricing Bridge'[cardNumber],
			    'Pricing Bridge'[id] IN {"8712", "19466", "1015", "16960", "16964"}, "1",
			    'Pricing Bridge'[id] IN {"2752", "2753", "17014", "17015"}, FORMAT('Pricing Bridge'[cardNumber], "000"),
			    AND('Pricing Bridge'[expansion.data.attributes.code]  IN {"SOR", "SHD", "TWI"}, OR(ISBLANK('Pricing Bridge'[variantTypes.data.attributes.name]), 'Pricing Bridge'[variantTypes.data.attributes.name] IN {"OP Promo", "OP Promo Foil", ""})), FORMAT('Pricing Bridge'[cardNumber], "00"),
			    'Pricing Bridge'[variantTypes.data.attributes.name] IN {"OP Promo Foil"}, FORMAT('Pricing Bridge'[cardNumber], "00"),
			    OR(ISBLANK('Pricing Bridge'[variantTypes.data.attributes.name]),'Pricing Bridge'[variantTypes.data.attributes.name] IN {"Judge Program", "OP Judge", "OP Promo", "OP Champion", "OP Finalist", "OP Top 4", "OP Top 8", "OP Top 16", ""}), 'Pricing Bridge'[cardNumber],
			    FORMAT('Pricing Bridge'[cardNumber], "000")
			)
			&
			//Suffix
			SWITCH(
			    TRUE(),
			    'Pricing Bridge'[id] IN {"8667", "8672", "8677", "8682", "8687", "8692", "8697", "8702", "2668", "1828", "2673", "1969", "2681", "1739", "1818", "2659", "15614", "15618", "15622", "15626", "15630", "15634", "15638", "15642"}, "/20",
			    'Pricing Bridge'[id] IN {"981", "982"}, "/" & 'Pricing Bridge'[cardCount],
			    'Pricing Bridge'[id] IN {"8664", "8834", "19456", "19461"}, "/002" & "_" & RELATED(Cards[title + subtitle]) & " (Hyperspace)",
			    'Pricing Bridge'[id] IN {"2752", "2753", "17014", "17015"}, "/" & FORMAT('Pricing Bridge'[cardCount], "000") & "_" & RELATED(Cards[title + subtitle]),
			    'Pricing Bridge'[id] IN {"17009", "17013", "8712", "19466", "1015", "16960", "16964"}, "/2" & "_" & RELATED(Cards[title + subtitle]),
			    'Pricing Bridge'[id] = {"2726"}, "/" & 'Pricing Bridge'[cardCount] & "_" & RELATED(Cards[title + subtitle]) & " (Surge Foil)",
			    AND('Pricing Bridge'[expansion.data.attributes.code]  IN {"SOR", "SHD", "TWI"}, OR(ISBLANK('Pricing Bridge'[variantTypes.data.attributes.name]), 'Pricing Bridge'[variantTypes.data.attributes.name] IN {"OP Promo", ""})), "/20",
			    AND('Pricing Bridge'[variantTypes.data.attributes.name] = "Standard", 'Pricing Bridge'[expansion.data.attributes.code] IN {"SOR", "SHD", "TWI"}), "/" & 'Pricing Bridge'[cardCount] & "_" & 'Pricing Bridge'[variantTypes.data.attributes.name],
			    AND('Pricing Bridge'[variantTypes.data.attributes.name] = "Standard Foil", 'Pricing Bridge'[expansion.data.attributes.code] IN {"SOR", "SHD", "TWI"}), "/" & 'Pricing Bridge'[cardCount] & "_Foil",
			    AND('Pricing Bridge'[variantTypes.data.attributes.name] = "Hyperspace", 'Pricing Bridge'[expansion.data.attributes.code] IN {"SOR", "SHD", "TWI"}), "_Standard",
			    AND('Pricing Bridge'[variantTypes.data.attributes.name] = "Hyperspace Foil", 'Pricing Bridge'[expansion.data.attributes.code] IN {"SOR", "SHD", "TWI"}), "_Foil",
			    AND('Pricing Bridge'[variantTypes.data.attributes.name] = "Showcase", 'Pricing Bridge'[expansion.data.attributes.code] IN {"SOR", "SHD", "TWI"}), "_Foil",
			    'Pricing Bridge'[variantTypes.data.attributes.name] = "Convention Exclusive", "/" & FORMAT('Pricing Bridge'[cardCount], "000"),
			    'Pricing Bridge'[variantTypes.data.attributes.name] = "Prerelease Promo", "/" & FORMAT('Pricing Bridge'[cardCount], "000") & "_" & RELATED(Cards[title + subtitle]),
			    'Pricing Bridge'[variantTypes.data.attributes.name] = "OP Judge", "/" & 'Pricing Bridge'[cardCount] & "_" & RELATED(Cards[title + subtitle]),
			    'Pricing Bridge'[variantTypes.data.attributes.name] = "Judge Program", "_" & RELATED(Cards[title + subtitle]),
			    'Pricing Bridge'[variantTypes.data.attributes.name] IN {"OP Champion", "OP Finalist", "OP Top 4", "OP Top 8", "OP Top 16"}, "/2" & "_" & RELATED(Cards[title + subtitle]) & " (" & RIGHT('Pricing Bridge'[variantTypes.data.attributes.name], LEN('Pricing Bridge'[variantTypes.data.attributes.name]) - 3) & ")",
			    'Pricing Bridge'[variantTypes.data.attributes.name] IN {"Standard"}, "/" & 'Pricing Bridge'[cardCount]
			)
			```
		lineageTag: 35f1265e-8d9a-49b1-9857-a0e2979dcb13
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column id
		dataType: string
		lineageTag: bc5d46bb-0e40-46d2-8282-88a0ef4802bb
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	partition 'Pricing Bridge' = m
		mode: import
		queryGroup: 'API Tables'
		source =
				let
				    Source = Base,
				    #"Removed Columns" = Table.RemoveColumns(Source,{"title", "subtitle", "artist", "artFrontHorizontal", "artBackHorizontal", "hasFoil", "cost", "hp", "power", "text", "textStyled", "deployBox", "deployBoxStyled", "epicAction", "epicActionStyled", "linkHtml", "createdAt", "updatedAt", "publishedAt", "locale", "hyperspace", "unique", "showcase", "rules", "rulesStyled", "serialCode", "upgradeHp", "upgradePower", "artFront", "artBack", "artThumbnail", "localizations", "aspects", "aspectDuplicates", "type.data.attributes.name", "type2", "traits", "arenas", "keywords", "rarity", "variantOf", "reprintOf", "validationId", "cardId"}),
				    #"Expanded expansion" = Table.ExpandRecordColumn(#"Removed Columns", "expansion", {"data"}, {"expansion.data"}),
				    #"Expanded expansion.data" = Table.ExpandRecordColumn(#"Expanded expansion", "expansion.data", {"id", "attributes"}, {"expansion.data.id", "expansion.data.attributes"}),
				    #"Expanded expansion.data.attributes" = Table.ExpandRecordColumn(#"Expanded expansion.data", "expansion.data.attributes", {"code"}, {"expansion.data.attributes.code"}),
				    #"Expanded variantTypes" = Table.ExpandRecordColumn(#"Expanded expansion.data.attributes", "variantTypes", {"data"}, {"variantTypes.data"}),
				    #"Expanded variantTypes.data" = Table.ExpandListColumn(#"Expanded variantTypes", "variantTypes.data"),
				    #"Expanded variantTypes.data1" = Table.ExpandRecordColumn(#"Expanded variantTypes.data", "variantTypes.data", {"id", "attributes"}, {"variantTypes.data.id", "variantTypes.data.attributes"}),
				    #"Expanded variantTypes.data.attributes" = Table.ExpandRecordColumn(#"Expanded variantTypes.data1", "variantTypes.data.attributes", {"name"}, {"variantTypes.data.attributes.name"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded variantTypes.data.attributes",{{"cardNumber", Int64.Type}, {"cardCount", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

