table Sets
	lineageTag: 53c5afd4-ed16-47ca-a5f1-525ba52cdd87

	column id
		dataType: string
		lineageTag: 2646c06a-6b28-4195-8b4b-3cc88dd5774a
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: 77783f7a-7191-416b-95bf-6d8f9036be25
		summarizeBy: none
		sourceColumn: name
		sortByColumn: sortValue

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: 6d752c69-3117-4e36-ab30-cc9d2a82b18f
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	column code
		dataType: string
		lineageTag: 961c0e5b-2a14-4a3d-ad39-23ee589e30db
		summarizeBy: none
		sourceColumn: code
		sortByColumn: sortValue

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column createdAt
		dataType: string
		lineageTag: 717486d3-0c74-4730-96d2-9562d7841354
		summarizeBy: none
		sourceColumn: createdAt

		annotation SummarizationSetBy = Automatic

	column updatedAt
		dataType: string
		lineageTag: a2b770b5-e0e8-4a5a-b078-a945bd547469
		summarizeBy: none
		sourceColumn: updatedAt

		annotation SummarizationSetBy = Automatic

	column publishedAt
		dataType: string
		lineageTag: e4f07cdf-54e7-4b01-96ce-d1910b64e9a5
		summarizeBy: none
		sourceColumn: publishedAt

		annotation SummarizationSetBy = Automatic

	column locale
		dataType: string
		lineageTag: 3f10a132-a3e3-41a6-875e-de8a6966d690
		summarizeBy: none
		sourceColumn: locale

		annotation SummarizationSetBy = Automatic

	column sortValue
		dataType: int64
		formatString: 0
		lineageTag: ca4a0b8a-2030-4807-b72a-e105a2348b41
		summarizeBy: none
		sourceColumn: sortValue

		annotation SummarizationSetBy = Automatic

	column image
		dataType: string
		lineageTag: 87a764c3-3f2e-4548-92fb-13bdbf19ec4f
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: image

		annotation SummarizationSetBy = Automatic

	column color
		dataType: string
		lineageTag: 61da5425-1093-4664-99b4-393ecf06ce83
		summarizeBy: none
		sourceColumn: color

		annotation SummarizationSetBy = Automatic

	partition Sets = m
		mode: import
		queryGroup: 'API Tables'
		source =
				let
				    Source = Base,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"expansion"}),
				    #"Expanded expansion" = Table.ExpandRecordColumn(#"Removed Other Columns", "expansion", {"data"}, {"data"}),
				    #"Expanded data" = Table.ExpandRecordColumn(#"Expanded expansion", "data", {"id", "attributes"}, {"id", "attributes"}),
				    #"Filtered Rows" = Table.SelectRows(#"Expanded data", each [id] <> null and [id] <> ""),
				    #"Expanded attributes" = Table.ExpandRecordColumn(#"Filtered Rows", "attributes", {"name", "description", "code", "createdAt", "updatedAt", "publishedAt", "locale", "sortValue"}, {"name", "description", "code", "createdAt", "updatedAt", "publishedAt", "locale", "sortValue"}),
				    #"Removed Duplicates" = Table.Distinct(#"Expanded attributes", {"id"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Duplicates",{{"sortValue", Int64.Type}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Changed Type", "image", each if [id] = 2 then "https://cdn.starwarsunlimited.com//xlarge_spark_of_rebellion_Logo_29fa5414fd.png" else if [id] = 8 then "https://cdn.starwarsunlimited.com//large_shadows_of_the_galaxy_Logo_91948b8327.png" else if [id] = 18 then "https://cdn.starwarsunlimited.com//xlarge_SWH_03_Twilight_of_the_Republic_Logo_e8e6d88851.png" else if [id] = 23 then "https://cdn.starwarsunlimited.com//large_SWH_04en_Logo_8e5408a592.png" else if [id] = 53 then "https://cdn.starwarsunlimited.com//medium_Legends_of_the_Force_Logo_dd1056bb3c.png" else "https://cdn.starwarsunlimited.com//medium_star_wars_unlimited_brand_logo_white_c33e64a77d.png"),
				    #"Added Conditional Column1" = Table.AddColumn(#"Added Conditional Column", "color", each if [id] = 2 then "#e10600" else if [id] = 8 then "#3b3fb6" else if [id] = 18 then "#7c2529" else if [id] = 23 then "#f2a900" else if [id] = 53 then "#00a3e0" else "#ffffff")
				in
				    #"Added Conditional Column1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

