table Sideboards
	lineageTag: efef7dbb-45fc-4f94-815e-4f8cbdbabdb0

	column 'Source.Name'
		dataType: string
		lineageTag: 1b4977dc-e494-45ab-b5f8-96c04f82792d
		summarizeBy: none
		sourceColumn: Source.Name

		annotation SummarizationSetBy = Automatic

	column 'metadata.name'
		dataType: string
		lineageTag: 1438237a-8cf1-4c84-b175-1e4e87517055
		summarizeBy: none
		sourceColumn: metadata.name

		annotation SummarizationSetBy = Automatic

	column 'metadata.author'
		dataType: string
		lineageTag: deac3a71-5308-4095-8c51-16cd4f67ac5b
		summarizeBy: none
		sourceColumn: metadata.author

		annotation SummarizationSetBy = Automatic

	column 'leader.id'
		dataType: string
		lineageTag: 39d61ae6-7a19-4972-958d-0cf48aefad7c
		summarizeBy: none
		sourceColumn: leader.id

		annotation SummarizationSetBy = Automatic

	column 'leader.count'
		dataType: int64
		formatString: 0
		lineageTag: 21d501bb-b38e-47b9-b922-7514c112b79e
		summarizeBy: sum
		sourceColumn: leader.count

		annotation SummarizationSetBy = Automatic

	column 'base.id'
		dataType: string
		lineageTag: 5542df13-789d-463b-9ba2-071fa0ef0b48
		summarizeBy: none
		sourceColumn: base.id

		annotation SummarizationSetBy = Automatic

	column 'base.count'
		dataType: int64
		formatString: 0
		lineageTag: 148de079-c920-452e-b99b-fb4c79ad0cac
		summarizeBy: sum
		sourceColumn: base.count

		annotation SummarizationSetBy = Automatic

	column 'sideboard.id'
		dataType: string
		lineageTag: a30ec68d-ee57-4948-85df-7e6e70ec2bc3
		summarizeBy: none
		sourceColumn: sideboard.id

		annotation SummarizationSetBy = Automatic

	column 'sideboard.count'
		dataType: string
		lineageTag: 2907219f-48ba-4dac-aa05-a6b916cd6782
		summarizeBy: none
		sourceColumn: sideboard.count

		annotation SummarizationSetBy = Automatic

	partition Sideboards = m
		mode: import
		queryGroup: 'Folder Tables'
		source =
				let
				    Source = Folder.Files(#"File Path" & "GitHub\swu-pbi-project\Decklists"),
				    #"Filtered Hidden Files1" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),
				    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File", each #"Transform File"([Content])),
				    #"Renamed Columns1" = Table.RenameColumns(#"Invoke Custom Function1", {"Name", "Source.Name"}),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns1", {"Source.Name", "Transform File"}),
				    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File", Table.ColumnNames(#"Transform File"(#"Sample File"))),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"Source.Name", type text}, {"metadata.name", type text}, {"metadata.author", type text}, {"leader.id", type text}, {"leader.count", Int64.Type}, {"base.id", type text}, {"base.count", Int64.Type}, {"deck", type any}, {"sideboard", type any}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"deck"}),
				    #"Expanded sideboard" = Table.ExpandListColumn(#"Removed Columns", "sideboard"),
				    #"Expanded sideboard1" = Table.ExpandRecordColumn(#"Expanded sideboard", "sideboard", {"id", "count"}, {"sideboard.id", "sideboard.count"})
				in
				    #"Expanded sideboard1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

